#!/usr/bin/env python3
"""
Step 0: SV Strict Filtering
============================================
Purpose: Filter UKB collapsed SVs using the original truth SV set (sv.final.lifted.hg38.vcf.gz).
Background: The collapsed VCF generated by truvari bench may contain false-positive or redundant SVs.
Filtering criteria:
  1. Same chromosome
  2. POS difference <= 1,000 bp
  3. Matched SVTYPE
    - Because the truth VCF may lack INFO/SVTYPE, this script infers SVTYPE from len(REF) and len(ALT) when needed (len(REF) > len(ALT) indicates DEL; otherwise INS).
    - DUP records in the UKB VCF are treated as INS in this comparison.
"""

import argparse
import gzip
import os
import sys

def infer_svtype(ref, alt, info_str=""):
    """
    Infer SVTYPE.
    1. First check whether INFO contains SVTYPE=
    2. Check whether ALT contains symbolic alleles such as <DEL>, <INS>, or <DUP>.
    3. If ALT is an explicit sequence, infer SVTYPE by comparing REF and ALT lengths.
    """
    # Try to extract SVTYPE from INFO
    for field in info_str.split(';'):
        if field.startswith('SVTYPE='):
            return field.split('=')[1].upper()
            
    # Try to extract SVTYPE from symbolic ALT <TYPE>
    if alt.startswith('<') and alt.endswith('>'):
        return alt[1:-1].upper()

    # Length-based inference
    # For multiallelic or complex records, use the first ALT allele only
    first_alt = alt.split(',')[0]
    
    # Handle possible placeholder alleles
    if first_alt == '.': 
        return "UNKNOWN"
        
    if len(ref) > len(first_alt):
        return "DEL"
    elif len(ref) < len(first_alt):
        return "INS"
    else:
        return "SNP_MNP" # Equal length; not an SV

def parse_truth_vcf(vcf_path):
    """Extract truth SVs: dict[chrom] -> list of (pos, svtype)"""
    truth_svs = {}
    count = 0
    with gzip.open(vcf_path, 'rt') as f:
        for line in f:
            if line.startswith('#'):
                continue
            fields = line.strip().split('\t')
            if len(fields) < 5:
                continue
            
            chrom = fields[0]
            pos = int(fields[1])
            ref = fields[3]
            alt = fields[4]
            info = fields[7] if len(fields) > 7 else ""
            
            svtype = infer_svtype(ref, alt, info)
            
            if chrom not in truth_svs:
                truth_svs[chrom] = []
            truth_svs[chrom].append((pos, svtype))
            count += 1
            
    print(f"  Extracted {count} truth SVs.")
    return truth_svs

def main():
    parser = argparse.ArgumentParser(description='Filter UKB SVs based on Truth SVs')
    parser.add_argument('--truth', required=True, help='Original Truth VCF (e.g. sv.final.lifted.hg38.vcf.gz)')
    parser.add_argument('--ukb', required=True, help='UKB Collapsed VCF (e.g. final.500k.collapsed.sort.vcf.gz)')
    parser.add_argument('--outdir', required=True, help='Output directory')
    args = parser.parse_args()

    os.makedirs(args.outdir, exist_ok=True)
    
    print(f"1. Loading truth SVs: {args.truth}")
    truth_svs = parse_truth_vcf(args.truth)
    
    print(f"\n2. Scanning and filtering UKB SVs: {args.ukb}")
    valid_ids = []
    matched_truth_counts = 0
    total_ukb = 0
    
    with gzip.open(args.ukb, 'rt') as f:
        for line in f:
            if line.startswith('#'):
                continue
                
            total_ukb += 1
            fields = line.strip().split('\t', 8)
            chrom = fields[0]
            pos = int(fields[1])
            sv_id = fields[2]
            ref = fields[3]
            alt = fields[4]
            info = fields[7]
            
            ukb_svtype = infer_svtype(ref, alt, info)
            # UKB-specific rule: treat DUP as INS when comparing against the truth set
            cmp_ukb_svtype = "INS" if ukb_svtype == "DUP" else ukb_svtype
            
            # Check for a match
            matched = False
            if chrom in truth_svs:
                for t_pos, t_type in truth_svs[chrom]:
                    if abs(pos - t_pos) <= 1000 and cmp_ukb_svtype == t_type:
                        matched = True
                        break
                        
            if matched:
                valid_ids.append(sv_id)
                matched_truth_counts += 1

    print(f"  Scanned {total_ukb} UKB SVs.")
    print(f"  Matched: {matched_truth_counts} SVs.")
    
    out_file = os.path.join(args.outdir, 'valid_ukb_sv_ids.txt')
    with open(out_file, 'w') as f:
        for sv_id in valid_ids:
            f.write(f"{sv_id}\n")
            
    print(f"\n3. Writing valid SV list: {out_file}")

if __name__ == '__main__':
    main()
